# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExploreUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ExploreUI
  pod 'SwipeViewController'

  target 'ExploreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExploreUIUITests' do
    # Pods for testing
  end

end
